services:
  - type: worker
    name: btc-5m-bot
    env: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: FIREBASE_PROJECT_ID
        value: btc-bot884
      - key: FIREBASE_DATABASE_URL
        value: https://btc-bot884-default-rtdb.firebaseio.com
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@btc-bot884.iam.gserviceaccount.com
      - key: FIREBASE_PRIVATE_KEY
        sync: false
